### ISSUE TITLE
Make NUM_DOORS and NUM_ITERATIONS command line arguments

### ISSUE THREAD

**Issue by karanparikh** [nihit/MontyHall#1]
Make `NUM_DOORS` and `NUM_ITERATIONS` command line arguments in `experiment.py`

**Comment by karanparikh** [comment]
Hi @nihit could you please assign this issue to me?

**Comment by nihit** [comment]
done.

**Comment by karanparikh** [comment]
@nihit here is the pull request https://github.com/nihit/MontyHall/pull/4

**Comment by karanparikh** [comment]
Fixed in f32fdb71c48c218b47fccd98b454e448d57722b3
